name: DiscordToServerMessage
main: space\yurisi\DiscordToServerMessage
author: yurisi
# depend:
#   - EconomyAPI
version: 1.0.0
api: 4.0.0
permissions:
  space.yurisi.DiscordToServerMessage.dtsm:
    default: op